// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ozst

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postId"`
	ParentID *string    `json:"parentId,omitempty"`
	Content  string     `json:"content"`
	Children []*Comment `json:"children"`
	Deep     int        `json:"deep"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Comments        []*Comment `json:"comments"`
	CommentsAllowed bool       `json:"commentsAllowed"`
}

type Query struct {
}
